CC = gcc
CFLAGS = -Wall -Wextra -std=c11
LDFLAGS = 

SRC = main.c funcoes.c
OBJ = $(SRC:.c=.o)
EXECUTABLE = projeto

.PHONY: all clean

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJ)
	$(CC) $(LDFLAGS) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXECUTABLE)
